# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule GraphApi.Schema.Beta.PasswordProfile do
  @moduledoc """
  Auto-generated schema for `microsoft.graph.passwordProfile`.
  """

  defstruct [
    :password,
    :force_change_password_next_sign_in,
    :force_change_password_next_sign_in_with_mfa
  ]

  @type t :: %__MODULE__{
          password: String.t() | nil,
          force_change_password_next_sign_in: boolean() | nil,
          force_change_password_next_sign_in_with_mfa: boolean() | nil
        }

  @field_mapping %{
    {"password", :password},
    {"forceChangePasswordNextSignIn", :force_change_password_next_sign_in},
    {"forceChangePasswordNextSignInWithMfa", :force_change_password_next_sign_in_with_mfa}
  }

  @field_names [
    "password",
    "forceChangePasswordNextSignIn",
    "forceChangePasswordNextSignInWithMfa"
  ]

  @doc "Mapping from camelCase API field names to snake_case struct atoms."
  @spec __field_mapping__() :: %{String.t() => atom()}
  def __field_mapping__, do: @field_mapping

  @doc "List of camelCase API field names (for OData `$select`)."
  @spec __field_names__() :: [String.t()]
  def __field_names__, do: @field_names

  @doc "Converts a camelCase string-key map (API response) into this struct."
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    %__MODULE__{
      password: map["password"],
      force_change_password_next_sign_in: map["forceChangePasswordNextSignIn"],
      force_change_password_next_sign_in_with_mfa: map["forceChangePasswordNextSignInWithMfa"]
    }
  end

  @doc "Converts this struct to a camelCase string-key map. Nil fields are omitted."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    [
      {"password", struct.password},
      {"forceChangePasswordNextSignIn", struct.force_change_password_next_sign_in},
      {"forceChangePasswordNextSignInWithMfa", struct.force_change_password_next_sign_in_with_mfa}
    ]
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
    |> Map.new()
  end
end
