# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule MicrosoftGraph.Schema.Beta.CalendarColor do
  @moduledoc """
  Auto-generated enum for `microsoft.graph.calendarColor`.
  """

  @values [
    "auto",
    "lightBlue",
    "lightGreen",
    "lightOrange",
    "lightGray",
    "lightYellow",
    "lightTeal",
    "lightPink",
    "lightBrown",
    "lightRed",
    "maxColor"
  ]

  @doc "Returns all valid enum values."
  @spec values() :: [String.t()]
  def values, do: @values

  @doc "Returns `true` if the given string is a valid enum value."
  @spec valid?(String.t()) :: boolean()
  def valid?(value) when is_binary(value), do: value in @values

  @doc "Returns the `\"auto\"` enum value."
  @spec auto() :: String.t()
  def auto, do: "auto"

  @doc "Returns the `\"lightBlue\"` enum value."
  @spec light_blue() :: String.t()
  def light_blue, do: "lightBlue"

  @doc "Returns the `\"lightGreen\"` enum value."
  @spec light_green() :: String.t()
  def light_green, do: "lightGreen"

  @doc "Returns the `\"lightOrange\"` enum value."
  @spec light_orange() :: String.t()
  def light_orange, do: "lightOrange"

  @doc "Returns the `\"lightGray\"` enum value."
  @spec light_gray() :: String.t()
  def light_gray, do: "lightGray"

  @doc "Returns the `\"lightYellow\"` enum value."
  @spec light_yellow() :: String.t()
  def light_yellow, do: "lightYellow"

  @doc "Returns the `\"lightTeal\"` enum value."
  @spec light_teal() :: String.t()
  def light_teal, do: "lightTeal"

  @doc "Returns the `\"lightPink\"` enum value."
  @spec light_pink() :: String.t()
  def light_pink, do: "lightPink"

  @doc "Returns the `\"lightBrown\"` enum value."
  @spec light_brown() :: String.t()
  def light_brown, do: "lightBrown"

  @doc "Returns the `\"lightRed\"` enum value."
  @spec light_red() :: String.t()
  def light_red, do: "lightRed"

  @doc "Returns the `\"maxColor\"` enum value."
  @spec max_color() :: String.t()
  def max_color, do: "maxColor"
end
