# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule MicrosoftGraph.Schema.Beta.DirectoryRole do
  @moduledoc """
  Auto-generated schema for `microsoft.graph.directoryRole`.
  """

  defstruct [:id, :deleted_date_time, :display_name, :description, :role_template_id]

  @type t :: %__MODULE__{
          id: String.t() | nil,
          deleted_date_time: String.t() | nil,
          display_name: String.t() | nil,
          description: String.t() | nil,
          role_template_id: String.t() | nil
        }

  @field_mapping %{
    {"id", :id},
    {"deletedDateTime", :deleted_date_time},
    {"displayName", :display_name},
    {"description", :description},
    {"roleTemplateId", :role_template_id}
  }

  @field_names [
    "id",
    "deletedDateTime",
    "displayName",
    "description",
    "roleTemplateId"
  ]

  @doc "Mapping from camelCase API field names to snake_case struct atoms."
  @spec __field_mapping__() :: %{String.t() => atom()}
  def __field_mapping__, do: @field_mapping

  @doc "List of camelCase API field names (for OData `$select`)."
  @spec __field_names__() :: [String.t()]
  def __field_names__, do: @field_names

  @doc "Converts a camelCase string-key map (API response) into this struct."
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    %__MODULE__{
      id: map["id"],
      deleted_date_time: map["deletedDateTime"],
      display_name: map["displayName"],
      description: map["description"],
      role_template_id: map["roleTemplateId"]
    }
  end

  @doc "Converts this struct to a camelCase string-key map. Nil fields are omitted."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    [
      {"id", struct.id},
      {"deletedDateTime", struct.deleted_date_time},
      {"displayName", struct.display_name},
      {"description", struct.description},
      {"roleTemplateId", struct.role_template_id}
    ]
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
    |> Map.new()
  end
end
