# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule MicrosoftGraph.Schema.Beta.Hashes do
  @moduledoc """
  Auto-generated schema for `microsoft.graph.hashes`.
  """

  defstruct [:sha1_hash, :sha256_hash, :quick_xor_hash]

  @type t :: %__MODULE__{
          sha1_hash: String.t() | nil,
          sha256_hash: String.t() | nil,
          quick_xor_hash: String.t() | nil
        }

  @field_mapping %{
    {"sha1Hash", :sha1_hash},
    {"sha256Hash", :sha256_hash},
    {"quickXorHash", :quick_xor_hash}
  }

  @field_names [
    "sha1Hash",
    "sha256Hash",
    "quickXorHash"
  ]

  @doc "Mapping from camelCase API field names to snake_case struct atoms."
  @spec __field_mapping__() :: %{String.t() => atom()}
  def __field_mapping__, do: @field_mapping

  @doc "List of camelCase API field names (for OData `$select`)."
  @spec __field_names__() :: [String.t()]
  def __field_names__, do: @field_names

  @doc "Converts a camelCase string-key map (API response) into this struct."
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    %__MODULE__{
      sha1_hash: map["sha1Hash"],
      sha256_hash: map["sha256Hash"],
      quick_xor_hash: map["quickXorHash"]
    }
  end

  @doc "Converts this struct to a camelCase string-key map. Nil fields are omitted."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    [
      {"sha1Hash", struct.sha1_hash},
      {"sha256Hash", struct.sha256_hash},
      {"quickXorHash", struct.quick_xor_hash}
    ]
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
    |> Map.new()
  end
end
