# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule MicrosoftGraph.Schema.Beta.Identity do
  @moduledoc """
  Auto-generated schema for `microsoft.graph.identity`.
  """

  defstruct [:display_name, :id]

  @type t :: %__MODULE__{
          display_name: String.t() | nil,
          id: String.t() | nil
        }

  @field_mapping %{
    {"displayName", :display_name},
    {"id", :id}
  }

  @field_names [
    "displayName",
    "id"
  ]

  @doc "Mapping from camelCase API field names to snake_case struct atoms."
  @spec __field_mapping__() :: %{String.t() => atom()}
  def __field_mapping__, do: @field_mapping

  @doc "List of camelCase API field names (for OData `$select`)."
  @spec __field_names__() :: [String.t()]
  def __field_names__, do: @field_names

  @doc "Converts a camelCase string-key map (API response) into this struct."
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    %__MODULE__{
      display_name: map["displayName"],
      id: map["id"]
    }
  end

  @doc "Converts this struct to a camelCase string-key map. Nil fields are omitted."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    [
      {"displayName", struct.display_name},
      {"id", struct.id}
    ]
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
    |> Map.new()
  end
end
