# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule GraphApi.Schema.Beta.BodyType do
  @moduledoc """
  Auto-generated enum for `microsoft.graph.bodyType`.
  """

  @values ["text", "html"]

  @doc "Returns all valid enum values."
  @spec values() :: [String.t()]
  def values, do: @values

  @doc "Returns `true` if the given string is a valid enum value."
  @spec valid?(String.t()) :: boolean()
  def valid?(value) when is_binary(value), do: value in @values

  @doc "Returns the `\"text\"` enum value."
  @spec text() :: String.t()
  def text, do: "text"

  @doc "Returns the `\"html\"` enum value."
  @spec html() :: String.t()
  def html, do: "html"
end
