# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule GraphApi.Schema.Beta.Importance do
  @moduledoc """
  Auto-generated enum for `microsoft.graph.importance`.
  """

  @values ["low", "normal", "high"]

  @doc "Returns all valid enum values."
  @spec values() :: [String.t()]
  def values, do: @values

  @doc "Returns `true` if the given string is a valid enum value."
  @spec valid?(String.t()) :: boolean()
  def valid?(value) when is_binary(value), do: value in @values

  @doc "Returns the `\"low\"` enum value."
  @spec low() :: String.t()
  def low, do: "low"

  @doc "Returns the `\"normal\"` enum value."
  @spec normal() :: String.t()
  def normal, do: "normal"

  @doc "Returns the `\"high\"` enum value."
  @spec high() :: String.t()
  def high, do: "high"
end
