# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule MicrosoftGraph.Schema.AssignedPlan do
  @moduledoc """
  Auto-generated schema for `microsoft.graph.assignedPlan`.
  """

  defstruct [:assigned_date_time, :capability_status, :service, :service_plan_id]

  @type t :: %__MODULE__{
          assigned_date_time: String.t() | nil,
          capability_status: String.t() | nil,
          service: String.t() | nil,
          service_plan_id: String.t() | nil
        }

  @field_mapping %{
    {"assignedDateTime", :assigned_date_time},
    {"capabilityStatus", :capability_status},
    {"service", :service},
    {"servicePlanId", :service_plan_id}
  }

  @field_names [
    "assignedDateTime",
    "capabilityStatus",
    "service",
    "servicePlanId"
  ]

  @doc "Mapping from camelCase API field names to snake_case struct atoms."
  @spec __field_mapping__() :: %{String.t() => atom()}
  def __field_mapping__, do: @field_mapping

  @doc "List of camelCase API field names (for OData `$select`)."
  @spec __field_names__() :: [String.t()]
  def __field_names__, do: @field_names

  @doc "Converts a camelCase string-key map (API response) into this struct."
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    %__MODULE__{
      assigned_date_time: map["assignedDateTime"],
      capability_status: map["capabilityStatus"],
      service: map["service"],
      service_plan_id: map["servicePlanId"]
    }
  end

  @doc "Converts this struct to a camelCase string-key map. Nil fields are omitted."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    [
      {"assignedDateTime", struct.assigned_date_time},
      {"capabilityStatus", struct.capability_status},
      {"service", struct.service},
      {"servicePlanId", struct.service_plan_id}
    ]
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
    |> Map.new()
  end
end
