# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule MicrosoftGraph.Schema.File do
  @moduledoc """
  Auto-generated schema for `microsoft.graph.file`.
  """

  defstruct [:mime_type, :hashes]

  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          hashes: MicrosoftGraph.Schema.Hashes.t() | nil
        }

  @field_mapping %{
    {"mimeType", :mime_type},
    {"hashes", :hashes}
  }

  @field_names [
    "mimeType",
    "hashes"
  ]

  @doc "Mapping from camelCase API field names to snake_case struct atoms."
  @spec __field_mapping__() :: %{String.t() => atom()}
  def __field_mapping__, do: @field_mapping

  @doc "List of camelCase API field names (for OData `$select`)."
  @spec __field_names__() :: [String.t()]
  def __field_names__, do: @field_names

  @doc "Converts a camelCase string-key map (API response) into this struct."
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    %__MODULE__{
      mime_type: map["mimeType"],
      hashes:
        case map["hashes"] do
          nil -> nil
          val -> MicrosoftGraph.Schema.Hashes.from_map(val)
        end
    }
  end

  @doc "Converts this struct to a camelCase string-key map. Nil fields are omitted."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    [
      {"mimeType", struct.mime_type},
      {"hashes",
       case struct.hashes do
         nil -> nil
         val -> MicrosoftGraph.Schema.Hashes.to_map(val)
       end}
    ]
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
    |> Map.new()
  end
end
