defmodule MicrosoftGraph.Schema.Generator.CodeGenerator do
  @moduledoc false
  # Produces Elixir source code strings for entity, complex type, and enum modules.
  #
  # The `context` map must include:
  #   - `:enum_names` — list of enum type name strings
  #   - `:namespace` — module namespace prefix, e.g. "MicrosoftGraph.Schema" or
  #                     "MicrosoftGraph.Schema.Beta"

  alias MicrosoftGraph.Schema.Generator.Naming

  @default_namespace "MicrosoftGraph.Schema"

  @doc """
  Generates source code for an entity module.

  The entity has flattened properties (inheritance already resolved).
  """
  @spec generate_entity(map(), map()) :: {String.t(), String.t()}
  def generate_entity(entity, context) do
    module_name = Naming.entity_to_module_name(entity.name)
    filename = Naming.camel_to_snake(entity.name) <> ".ex"
    code = generate_struct_module(module_name, entity.properties, context)
    {filename, code}
  end

  @doc """
  Generates source code for a complex type module.
  """
  @spec generate_complex_type(map(), map()) :: {String.t(), String.t()}
  def generate_complex_type(complex_type, context) do
    module_name = Naming.entity_to_module_name(complex_type.name)
    filename = Naming.camel_to_snake(complex_type.name) <> ".ex"
    code = generate_struct_module(module_name, complex_type.properties, context)
    {filename, code}
  end

  @doc """
  Generates source code for an enum module.
  """
  @spec generate_enum(map(), map()) :: {String.t(), String.t()}
  def generate_enum(enum_type, context \\ %{}) do
    module_name = Naming.entity_to_module_name(enum_type.name)
    filename = Naming.camel_to_snake(enum_type.name) <> ".ex"
    code = generate_enum_module(module_name, enum_type, context)
    {filename, code}
  end

  # -- Struct module generation (entity + complex type) --

  defp generate_struct_module(module_name, properties, context) do
    ns = namespace(context)
    fields = Enum.map(properties, &property_to_field/1)
    field_atoms = Enum.map(fields, fn f -> f.atom end)

    field_mapping_entries =
      Enum.map_join(fields, ",\n", fn f ->
        ~s|    {"#{f.camel_name}", :#{f.atom}}|
      end)

    field_names_entries =
      Enum.map_join(fields, ",\n", fn f ->
        ~s|    "#{f.camel_name}"|
      end)

    typespec_fields =
      Enum.map_join(fields, ",\n", fn f ->
        "          #{f.atom}: #{elixir_typespec(f.type, context)} | nil"
      end)

    from_map_clauses =
      Enum.map_join(fields, ",\n", fn f ->
        cast_expr = from_map_cast(f.camel_name, f.type, context)
        "      #{f.atom}: #{cast_expr}"
      end)

    to_map_clauses =
      Enum.map_join(fields, ",\n", fn f ->
        cast_expr = to_map_cast("struct.#{f.atom}", f.type, context)
        ~s|      {"#{f.camel_name}", #{cast_expr}}|
      end)

    odata_name = raw_name_from_module(module_name)

    """
    # This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
    defmodule #{ns}.#{module_name} do
      @moduledoc \"""
      Auto-generated schema for `microsoft.graph.#{odata_name}`.
      \"""

      defstruct #{inspect(field_atoms)}

      @type t :: %__MODULE__{
    #{typespec_fields}
            }

      @field_mapping %{
    #{field_mapping_entries}
      }

      @field_names [
    #{field_names_entries}
      ]

      @doc "Mapping from camelCase API field names to snake_case struct atoms."
      @spec __field_mapping__() :: %{String.t() => atom()}
      def __field_mapping__, do: @field_mapping

      @doc "List of camelCase API field names (for OData `$select`)."
      @spec __field_names__() :: [String.t()]
      def __field_names__, do: @field_names

      @doc "Converts a camelCase string-key map (API response) into this struct."
      @spec from_map(map()) :: t()
      def from_map(map) when is_map(map) do
        %__MODULE__{
    #{from_map_clauses}
        }
      end

      @doc "Converts this struct to a camelCase string-key map. Nil fields are omitted."
      @spec to_map(t()) :: map()
      def to_map(%__MODULE__{} = struct) do
        [
    #{to_map_clauses}
        ]
        |> Enum.reject(fn {_k, v} -> is_nil(v) end)
        |> Map.new()
      end
    end
    """
  end

  # -- Enum module generation --

  defp generate_enum_module(module_name, enum_type, context) do
    ns = namespace(context)
    values = Enum.map(enum_type.members, & &1.name)

    value_functions =
      Enum.map_join(enum_type.members, "\n\n", fn member ->
        func_name = Naming.camel_to_snake(member.name)

        """
          @doc "Returns the `\\"#{member.name}\\"` enum value."
          @spec #{func_name}() :: String.t()
          def #{func_name}, do: "#{member.name}"\
        """
      end)

    odata_name = raw_name_from_module(module_name)

    """
    # This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
    defmodule #{ns}.#{module_name} do
      @moduledoc \"""
      Auto-generated enum for `microsoft.graph.#{odata_name}`.
      \"""

      @values #{inspect(values)}

      @doc "Returns all valid enum values."
      @spec values() :: [String.t()]
      def values, do: @values

      @doc "Returns `true` if the given string is a valid enum value."
      @spec valid?(String.t()) :: boolean()
      def valid?(value) when is_binary(value), do: value in @values

    #{value_functions}
    end
    """
  end

  # -- Helpers --

  defp namespace(context), do: context[:namespace] || @default_namespace

  defp property_to_field(property) do
    %{
      camel_name: property.name,
      atom: Naming.property_to_field(property.name),
      type: property.type
    }
  end

  defp raw_name_from_module(module_name) do
    <<first::utf8, rest::binary>> = module_name
    String.downcase(<<first::utf8>>) <> rest
  end

  @doc false
  def elixir_typespec(type, context) do
    ns = namespace(context)

    case type do
      "Edm.String" -> "String.t()"
      "Edm.Guid" -> "String.t()"
      "Edm.DateTimeOffset" -> "String.t()"
      "Edm.Date" -> "String.t()"
      "Edm.Binary" -> "String.t()"
      "Edm.Boolean" -> "boolean()"
      "Edm.Int32" -> "integer()"
      "Edm.Int64" -> "integer()"
      "Edm.Double" -> "float()"
      "Edm.Single" -> "float()"
      "Edm.Stream" -> "String.t()"
      "Collection(" <> rest ->
        inner = String.trim_trailing(rest, ")")
        "[#{elixir_typespec(inner, context)}]"
      "microsoft.graph." <> name ->
        mod = Naming.entity_to_module_name(name)
        if is_enum_type?(name, context) do
          "String.t()"
        else
          "#{ns}.#{mod}.t()"
        end
      _ ->
        "term()"
    end
  end

  defp from_map_cast(camel_name, type, context) do
    ns = namespace(context)
    access = ~s|map["#{camel_name}"]|

    case type do
      "Edm." <> _ ->
        access

      "Collection(microsoft.graph." <> rest ->
        inner_name = String.trim_trailing(rest, ")")
        mod = Naming.entity_to_module_name(inner_name)

        if is_enum_type?(inner_name, context) do
          access
        else
          "case #{access} do nil -> nil; items -> Enum.map(items, &#{ns}.#{mod}.from_map/1) end"
        end

      "Collection(Edm." <> _ ->
        access

      "microsoft.graph." <> name ->
        mod = Naming.entity_to_module_name(name)

        if is_enum_type?(name, context) do
          access
        else
          "case #{access} do nil -> nil; val -> #{ns}.#{mod}.from_map(val) end"
        end

      _ ->
        access
    end
  end

  defp to_map_cast(accessor, type, context) do
    ns = namespace(context)

    case type do
      "Edm." <> _ ->
        accessor

      "Collection(microsoft.graph." <> rest ->
        inner_name = String.trim_trailing(rest, ")")
        mod = Naming.entity_to_module_name(inner_name)

        if is_enum_type?(inner_name, context) do
          accessor
        else
          "case #{accessor} do nil -> nil; items -> Enum.map(items, &#{ns}.#{mod}.to_map/1) end"
        end

      "Collection(Edm." <> _ ->
        accessor

      "microsoft.graph." <> name ->
        mod = Naming.entity_to_module_name(name)

        if is_enum_type?(name, context) do
          accessor
        else
          "case #{accessor} do nil -> nil; val -> #{ns}.#{mod}.to_map(val) end"
        end

      _ ->
        accessor
    end
  end

  defp is_enum_type?(name, context) do
    name in (context[:enum_names] || [])
  end
end
