# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule GraphApi.Schema.Application do
  @moduledoc """
  Auto-generated schema for `microsoft.graph.application`.
  """

  defstruct [:id, :deleted_date_time, :display_name, :app_id, :sign_in_audience, :web]

  @type t :: %__MODULE__{
          id: String.t() | nil,
          deleted_date_time: String.t() | nil,
          display_name: String.t() | nil,
          app_id: String.t() | nil,
          sign_in_audience: String.t() | nil,
          web: GraphApi.Schema.WebApplication.t() | nil
        }

  @field_mapping %{
    {"id", :id},
    {"deletedDateTime", :deleted_date_time},
    {"displayName", :display_name},
    {"appId", :app_id},
    {"signInAudience", :sign_in_audience},
    {"web", :web}
  }

  @field_names [
    "id",
    "deletedDateTime",
    "displayName",
    "appId",
    "signInAudience",
    "web"
  ]

  @doc "Mapping from camelCase API field names to snake_case struct atoms."
  @spec __field_mapping__() :: %{String.t() => atom()}
  def __field_mapping__, do: @field_mapping

  @doc "List of camelCase API field names (for OData `$select`)."
  @spec __field_names__() :: [String.t()]
  def __field_names__, do: @field_names

  @doc "Converts a camelCase string-key map (API response) into this struct."
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    %__MODULE__{
      id: map["id"],
      deleted_date_time: map["deletedDateTime"],
      display_name: map["displayName"],
      app_id: map["appId"],
      sign_in_audience: map["signInAudience"],
      web:
        case map["web"] do
          nil -> nil
          val -> GraphApi.Schema.WebApplication.from_map(val)
        end
    }
  end

  @doc "Converts this struct to a camelCase string-key map. Nil fields are omitted."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    [
      {"id", struct.id},
      {"deletedDateTime", struct.deleted_date_time},
      {"displayName", struct.display_name},
      {"appId", struct.app_id},
      {"signInAudience", struct.sign_in_audience},
      {"web",
       case struct.web do
         nil -> nil
         val -> GraphApi.Schema.WebApplication.to_map(val)
       end}
    ]
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
    |> Map.new()
  end
end
