# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule GraphApi.Schema.Location do
  @moduledoc """
  Auto-generated schema for `microsoft.graph.location`.
  """

  defstruct [:display_name, :address]

  @type t :: %__MODULE__{
          display_name: String.t() | nil,
          address: GraphApi.Schema.PhysicalAddress.t() | nil
        }

  @field_mapping %{
    {"displayName", :display_name},
    {"address", :address}
  }

  @field_names [
    "displayName",
    "address"
  ]

  @doc "Mapping from camelCase API field names to snake_case struct atoms."
  @spec __field_mapping__() :: %{String.t() => atom()}
  def __field_mapping__, do: @field_mapping

  @doc "List of camelCase API field names (for OData `$select`)."
  @spec __field_names__() :: [String.t()]
  def __field_names__, do: @field_names

  @doc "Converts a camelCase string-key map (API response) into this struct."
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    %__MODULE__{
      display_name: map["displayName"],
      address:
        case map["address"] do
          nil -> nil
          val -> GraphApi.Schema.PhysicalAddress.from_map(val)
        end
    }
  end

  @doc "Converts this struct to a camelCase string-key map. Nil fields are omitted."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    [
      {"displayName", struct.display_name},
      {"address",
       case struct.address do
         nil -> nil
         val -> GraphApi.Schema.PhysicalAddress.to_map(val)
       end}
    ]
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
    |> Map.new()
  end
end
