# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule GraphApi.Schema.Organization do
  @moduledoc """
  Auto-generated schema for `microsoft.graph.organization`.
  """

  defstruct [:id, :deleted_date_time, :display_name, :verified_domains, :assigned_plans]

  @type t :: %__MODULE__{
          id: String.t() | nil,
          deleted_date_time: String.t() | nil,
          display_name: String.t() | nil,
          verified_domains: [GraphApi.Schema.VerifiedDomain.t()] | nil,
          assigned_plans: [GraphApi.Schema.AssignedPlan.t()] | nil
        }

  @field_mapping %{
    {"id", :id},
    {"deletedDateTime", :deleted_date_time},
    {"displayName", :display_name},
    {"verifiedDomains", :verified_domains},
    {"assignedPlans", :assigned_plans}
  }

  @field_names [
    "id",
    "deletedDateTime",
    "displayName",
    "verifiedDomains",
    "assignedPlans"
  ]

  @doc "Mapping from camelCase API field names to snake_case struct atoms."
  @spec __field_mapping__() :: %{String.t() => atom()}
  def __field_mapping__, do: @field_mapping

  @doc "List of camelCase API field names (for OData `$select`)."
  @spec __field_names__() :: [String.t()]
  def __field_names__, do: @field_names

  @doc "Converts a camelCase string-key map (API response) into this struct."
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    %__MODULE__{
      id: map["id"],
      deleted_date_time: map["deletedDateTime"],
      display_name: map["displayName"],
      verified_domains:
        case map["verifiedDomains"] do
          nil -> nil
          items -> Enum.map(items, &GraphApi.Schema.VerifiedDomain.from_map/1)
        end,
      assigned_plans:
        case map["assignedPlans"] do
          nil -> nil
          items -> Enum.map(items, &GraphApi.Schema.AssignedPlan.from_map/1)
        end
    }
  end

  @doc "Converts this struct to a camelCase string-key map. Nil fields are omitted."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    [
      {"id", struct.id},
      {"deletedDateTime", struct.deleted_date_time},
      {"displayName", struct.display_name},
      {"verifiedDomains",
       case struct.verified_domains do
         nil -> nil
         items -> Enum.map(items, &GraphApi.Schema.VerifiedDomain.to_map/1)
       end},
      {"assignedPlans",
       case struct.assigned_plans do
         nil -> nil
         items -> Enum.map(items, &GraphApi.Schema.AssignedPlan.to_map/1)
       end}
    ]
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
    |> Map.new()
  end
end
