# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule GraphApi.Schema.Sensitivity do
  @moduledoc """
  Auto-generated enum for `microsoft.graph.sensitivity`.
  """

  @values ["normal", "personal", "private", "confidential"]

  @doc "Returns all valid enum values."
  @spec values() :: [String.t()]
  def values, do: @values

  @doc "Returns `true` if the given string is a valid enum value."
  @spec valid?(String.t()) :: boolean()
  def valid?(value) when is_binary(value), do: value in @values

  @doc "Returns the `\"normal\"` enum value."
  @spec normal() :: String.t()
  def normal, do: "normal"

  @doc "Returns the `\"personal\"` enum value."
  @spec personal() :: String.t()
  def personal, do: "personal"

  @doc "Returns the `\"private\"` enum value."
  @spec private() :: String.t()
  def private, do: "private"

  @doc "Returns the `\"confidential\"` enum value."
  @spec confidential() :: String.t()
  def confidential, do: "confidential"
end
