# This file is auto-generated by `mix graph.gen.schema`. Do not edit manually.
defmodule GraphApi.Schema.WebApplication do
  @moduledoc """
  Auto-generated schema for `microsoft.graph.webApplication`.
  """

  defstruct [:redirect_uris, :home_page_url, :logout_url]

  @type t :: %__MODULE__{
          redirect_uris: [String.t()] | nil,
          home_page_url: String.t() | nil,
          logout_url: String.t() | nil
        }

  @field_mapping %{
    {"redirectUris", :redirect_uris},
    {"homePageUrl", :home_page_url},
    {"logoutUrl", :logout_url}
  }

  @field_names [
    "redirectUris",
    "homePageUrl",
    "logoutUrl"
  ]

  @doc "Mapping from camelCase API field names to snake_case struct atoms."
  @spec __field_mapping__() :: %{String.t() => atom()}
  def __field_mapping__, do: @field_mapping

  @doc "List of camelCase API field names (for OData `$select`)."
  @spec __field_names__() :: [String.t()]
  def __field_names__, do: @field_names

  @doc "Converts a camelCase string-key map (API response) into this struct."
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    %__MODULE__{
      redirect_uris: map["redirectUris"],
      home_page_url: map["homePageUrl"],
      logout_url: map["logoutUrl"]
    }
  end

  @doc "Converts this struct to a camelCase string-key map. Nil fields are omitted."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    [
      {"redirectUris", struct.redirect_uris},
      {"homePageUrl", struct.home_page_url},
      {"logoutUrl", struct.logout_url}
    ]
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
    |> Map.new()
  end
end
